server.port: 8080

info:
  build:
    artifact: "@project.artifactId@"
    description: "@project.description@"
    version: "@project.version@"

logging.level.root: INFO

mongo:
  host: 127.0.0.1
  port: 27017
  db.name: test

spring.jackson:
  default-property-inclusion: non_null