name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: test with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: test
